# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f9f0feffeac51308f7afd6ee5768beef357b1ce1645867b6ad82d2e2a6ca9f148fa48861d169646d53261d81eae1655e86087ef254343f37ac8094ef4a95433

test:
  secret_key_base: e2843930d75f80aad1e13ffce57316f881b8d0e574015efb0b5c1a71e826bf53b4ee228796619494701fa177f38901149fc496bf098e9ac3d5d7db2468073a53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
